export const slugs = {
  timmy: 'timmy',
  reanimatedHand: 'reanimated-hand',
  headHoncho: 'head-honcho',
  misterBribe: 'mister-bribe',
  billionaireChest: 'billionaire-chest',
  harbinger: 'harbinger',
  chester: 'chester',
  scripticus: 'scripticus',
  esquire: 'esquire-bored-bean',
  gratefulbinger: 'gratefulbinger',
  coolBird: 'cool-bird',
  chippy: 'chippy',
  ghost: 'ghost',
  grumblo: 'grumblo',
  fizarreDrink: 'fizarre-drink',
  rupieSlug: 'rupie-slug',
  poppy: 'poppy',
} as const;
